#!/usr/bin/env bash
FILE="$1"
MSG="$2"

if [ -e "$FILE" ]; then
	echo "File exists"
	exit 1
fi
if [ -z "$FILE" ]; then
        echo "File Name needed"
        exit 1
fi
if [ -z "$MSG" ]; then
	MSG="Committing change"
fi

printf "#!/usr/bin/env ruby\nputs ARGV[0].scan(/127.0.0.[0-9]/).join" > $FILE
